### ISSUE TITLE
Wrong rounding of lat and lng when decimal places are separated with comma

### ISSUE THREAD

**Issue by philippze** [Organice/djangocms-maps#9]
Seen with osm.

In German, we separate decimal places with a comma instead with a period like in English.

Hence, `parseFloat(data.lat)` will not work correctly. The decimal places of latitude and longitude are ignored.

I'll create a pull request that fixes this for Openstreetmap.

**Comment by MacLake** [comment]
I also get wrong coordinates when using Google maps in the current Pypi version 0.7.0 , probably also in this case the decimal fraction after "." or ",'" is clipped.

**Comment by bittner** [comment]
@MacLake Thanks for pointing this out!

Could you try to make the same changes as in #10 to [googlemaps.js (line 71)](https://github.com/Organice/djangocms-maps/blob/master/djangocms_maps/static/djangocms_maps/js/googlemaps.js#L71), and see if this fixes the issue?

**Comment by bittner** [comment]
It would be cool if we had tests for this kind of problem. Really, I guess this would be pretty hard to get going (German UI test environment, probably with Selenium running on Travis).

**Comment by bittner** [comment]
Fixed for all remaining services via 6728bef20f45f24d0f9797c9a5ebf8f4fa2d68b5.

@MacLake Can you test whether the latest `master` works for you now? I would then push a new release to PyPI.

**Comment by bittner** [comment]
[Version 0.8.0 released](https://pypi.python.org/pypi/djangocms-maps) on PyPI.
